"""empty message

Revision ID: 4cd3d2d5a8e7
Revises: 1589f4f81650
Create Date: 2025-05-10 18:52:20.607643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd3d2d5a8e7'
down_revision = '1589f4f81650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_certified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_certified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
