"""empty message

Revision ID: 4fb6f1190e9d
Revises: 5e9e4a5c3c42
Create Date: 2025-04-28 21:55:26.413376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb6f1190e9d'
down_revision = '5e9e4a5c3c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=100), nullable=True),
    sa.Column('answers', sa.VARCHAR(length=300), nullable=True),
    sa.Column('right_answer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('question_count', sa.INTEGER(), nullable=True),
    sa.Column('answer_on_question', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
