"""empty message

Revision ID: ef9a4ac896ea
Revises: 273d860fc6b8
Create Date: 2025-04-12 20:06:46.763038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9a4ac896ea'
down_revision = '273d860fc6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('password_confirmation', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_teacher', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_teacher')
        batch_op.drop_column('password_confirmation')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
